eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: cloud-app #服务名称
    ribbon.eureka.enable: true
#  devtools:
#        restart:
#          enabled: true
